[features]
seeds = false
skip-lint = false
[programs.localnet]
batch_transfer = "knWFUzBZJVp5yxkqA9w9UH3dv3qHm2LiVzV67rcHGQd"

[programs.devnet]
batch_transfer = "knWFUzBZJVp5yxkqA9w9UH3dv3qHm2LiVzV67rcHGQd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id_4.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
