[features]
seeds = false
skip-lint = false
[programs.localnet]
batch_transfer = "DwZruo6t3BW4DUtALe2i2E6ewA8b5mH1Lk2TWeyV8ymo"

[programs.devnet]
batch_transfer = "DwZruo6t3BW4DUtALe2i2E6ewA8b5mH1Lk2TWeyV8ymo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id_4.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
